#!/bin/bash

echo "🔍 Проверка статуса Fonana..."
echo ""
echo "📌 КОМАНДЫ ДЛЯ ВЫПОЛНЕНИЯ НА СЕРВЕРЕ:"
echo "========================================="
echo ""
echo "# 1. Подключитесь к серверу:"
echo "ssh -p 43988 root@fonana.me"
echo ""
echo "# 2. Проверьте статус:"
echo "cd /var/www/fonana"
echo "systemctl status fonana"
echo ""
echo "# 3. Проверьте логи:"
echo "journalctl -u fonana -n 50 --no-pager"
echo ""
echo "# 4. Проверьте версию кода:"
echo "ls -la"
echo "cat package.json | grep version"
echo ""
echo "=========================================" 