version: '3.8'

services:
  fonana:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - fonana-network

networks:
  fonana-network:
    driver: bridge 