# Docker Compose for LOCAL DEVELOPMENT ONLY
# DO NOT use this in production yet!

version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fonana_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fonana_dev
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: dev-secret-change-me
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db
    command: npm run dev

volumes:
  postgres_data: 