#!/bin/bash

echo "🔧 Исправление путей в конфигурации nginx для Fonana..."

# Команды для выполнения на сервере
echo "Выполните следующие команды на сервере:"
echo ""
echo "# 1. Подключитесь к серверу:"
echo "ssh -p 43988 root@69.10.59.234"
echo ""
echo "# 2. Создайте резервную копию текущей конфигурации:"
echo "cp /etc/nginx/sites-available/fonana /etc/nginx/sites-available/fonana.backup"
echo ""
echo "# 3. Обновите конфигурацию nginx (откройте файл в редакторе):"
echo "nano /etc/nginx/sites-available/fonana"
echo ""
echo "# 4. Найдите и исправьте следующие строки:"
echo ""
echo "БЫЛО:"
echo "    location /_next/static/ {"
echo "        alias /var/www/.next/static/;"
echo ""
echo "СТАЛО:"
echo "    location /_next/static/ {"
echo "        alias /var/www/fonana/.next/static/;"
echo ""
echo "БЫЛО:"
echo "    location /public/ {"
echo "        alias /var/www/public/;"
echo ""
echo "СТАЛО:"
echo "    location /public/ {"
echo "        alias /var/www/fonana/public/;"
echo ""
echo "БЫЛО:"
echo "        root /var/www/public;"
echo ""
echo "СТАЛО:"
echo "        root /var/www/fonana/public;"
echo ""
echo "# 5. Сохраните файл (Ctrl+X, Y, Enter)"
echo ""
echo "# 6. Проверьте конфигурацию:"
echo "nginx -t"
echo ""
echo "# 7. Перезапустите nginx:"
echo "systemctl reload nginx"
echo ""
echo "# 8. Проверьте статус:"
echo "systemctl status nginx"
echo ""
echo "# 9. Проверьте доступность статических файлов:"
echo "curl -I https://fonana.me/_next/static/chunks/webpack-f9a8923f791c7231.js"
echo ""
echo "✅ После этих изменений статические файлы должны загружаться корректно!" 