#!/bin/bash

# Скрипт для настройки SSH конфигурации на сервере Fonana
# Автор: AI Assistant

echo "🔧 Настройка SSH конфигурации для сервера Fonana"
echo "==============================================="

# Цвета для вывода
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Проверка прав root
if [ "$EUID" -ne 0 ]; then
    log_error "Этот скрипт должен запускаться от имени root"
    exit 1
fi

SSH_CONFIG="/etc/ssh/sshd_config"

# Создание backup
log_info "Создание backup конфигурации SSH..."
cp $SSH_CONFIG $SSH_CONFIG.backup.$(date +%Y%m%d_%H%M%S)

# Настройка SSH конфигурации
log_info "Настройка SSH конфигурации..."

# Создаем временный файл с настройками
cat > /tmp/ssh_config_updates << 'EOF'
# SSH Configuration for Fonana Server
# Generated by setup script

# Основные настройки безопасности
Port 22
Protocol 2

# Аутентификация по ключам
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys

# Отключаем небезопасные методы аутентификации
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM no

# Настройки безопасности
PermitRootLogin yes
StrictModes yes
MaxAuthTries 3
MaxSessions 10

# Настройки соединения
ClientAliveInterval 300
ClientAliveCountMax 2
TCPKeepAlive yes

# Логирование
SyslogFacility AUTH
LogLevel INFO

# Отключаем неиспользуемые функции
X11Forwarding no
PrintMotd no
PrintLastLog yes
AcceptEnv LANG LC_*

# Настройки для производительности
Compression yes
EOF

# Применяем настройки
log_info "Применение новых настроек SSH..."
cp /tmp/ssh_config_updates $SSH_CONFIG

# Устанавливаем правильные права
chmod 644 $SSH_CONFIG
chown root:root $SSH_CONFIG

# Проверяем конфигурацию
log_info "Проверка конфигурации SSH..."
if sshd -t; then
    log_success "Конфигурация SSH корректна"
else
    log_error "Ошибка в конфигурации SSH!"
    log_info "Восстанавливаем backup..."
    cp $SSH_CONFIG.backup.$(date +%Y%m%d_%H%M%S) $SSH_CONFIG
    exit 1
fi

# Перезапускаем SSH сервис
log_info "Перезапуск SSH сервиса..."
systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>/dev/null

if systemctl is-active --quiet ssh || systemctl is-active --quiet sshd; then
    log_success "SSH сервис успешно перезапущен"
else
    log_error "Ошибка при перезапуске SSH сервиса!"
fi

# Проверяем статус
log_info "Текущий статус SSH сервиса:"
systemctl status ssh 2>/dev/null || systemctl status sshd 2>/dev/null

log_success "Настройка SSH конфигурации завершена!"
echo ""
log_info "Важные изменения:"
echo "- Включена аутентификация по ключам"
echo "- Отключена аутентификация по паролю"
echo "- Настроены параметры безопасности"
echo "- SSH сервис перезапущен"

echo ""
log_warning "ВНИМАНИЕ: Убедитесь, что SSH ключи настроены перед отключением!"
echo "Для тестирования используйте: ssh -i /path/to/key root@$(hostname -I | awk '{print $1}')"
